const hotels = [
  'ballys_las_vegas',
  'the_belvedere_hotel',
  'astor_hotel_3',
  'maldron_hotel_parnell_square',
  'monument_hotel_2',
  'grange_st_pauls',
  'puerta_america_hotel',
  'park_inn_by_radisson_berlin_alexanderplatz_2',
  'intercontinental_warsaw',
  'altis_prime_hotel_de_apartamentos',
  'wellington_hotel_2',
  'gran_melia_fenix',
  'axel_hotel_madrid_adults_only',
  'hotel_puerta_de_toledo',
  'petit_palace_mayor_plaza',
  'hotel_maria_elena_palace',
  'husa_paseo_del_arte',
  'eurostars_hotel_plaza_mayor',
  'hotel_exe_moncloa',
  'hotel_exe_central',
  'hotel_t3_tirol',
  'hotel_ganivet',
  '_0x7c6bf',
  'urban',
  'abba_castilla_plaza_hotel',
  'aparthotel_orion',
  'exe_el_coloso',
  'catalonia_hotel_plaza_mayor',
  'umusic_hotel_madrid',
  'agora_juan_de_austria',
  'nh_embajada',
  'catalonia_hotel_las_cortes',
  'hotel_petit_palace_alcala_torre',
  'rafaelhoteles_atocha_hotel',
  'the_social_hub_madrid_4',
  'hotel_acta_madfor',
  'vp_plaza_espana_design',
  'senator_barajas',
  'catalonia_hotel_atocha',
  'pullman_london_st_pancras_2',
  'the_danubius_hotel__london_regents_park',
  'the_tower_a_guoman_hotel',
  'hotel_ibis_london_earls_court',
  'grange_city_hotel',
  'wombats_city_hostel_london',
  'grange_wellington_hotel',
  'travelodge_london_heathrow_central',
  'thistle_kensington_gardens',
  'lancaster_court_hotel_2',
  'mondrian_london',
  'park_plaza_riverbank_london',
  'charing_cross',
  'best_western_phoenix_hotel',
  'crown_moran_hotel',
  'leman_locke',
  'the_montcalm_at_brewery_london_city',
  'grange_tower_bridge',
  'bloomsbury_park_a_thistle_associate_hotel',
  'holiday_inn_london_heathrow_ariel',
  'tower_suites',
  'premier_inn_london_blackfriars',
  'le_meridien_piccadilly',
  'hotel_ornato',
  'hotel_berna',
  'the_square_milano_duomo',
  'j24_hotel_milano',
  'hotel_la_residenza_2',
  'klima_hotel_milano_fiere',
  'una_hotel_cusani',
  'best_western_plus_hotel_felice_casati',
  'ramada_plaza_milano_2',
  'leonardo_da_vinci_hotel',
  'best_western_atlantic',
  'hotel_raffaello_2',
  'starhotels_rosa_grand_milano',
  'galileo_hotel',
  'duca_2',
  'hotel_degli_arcimboldi',
  'crivis',
  'max_brown_hotel_missori_part_of_sircle_collection',
  'hotel_san_francisco_5',
  'mennini_hotel',
  'hotel_zefiro',
  'starhotels_echo',
  'hotel_regency',
  'duomoapartments_by_nomad_aparthotels',
  'best_western_plus_president_hotel_at_times_square',
  'the_belvedere_hotel',
  'pod_51',
  'night_hotel_times_square',
  'the_manhattan_at_times_square_hotel',
  'holiday_inn_new_york__times_square_south',
  'pod_times_square',
  'la_quinta_manhattan',
  'empire_hotel',
  'hotel_mint_jfk_airport',
  'pod_39',
  'walker_hotel_tribeca',
  'park_central_new_york',
  'the_paramount__a_times_square_new_york_hotel',
  'hotel_indigo_lower_east_side_new_york',
];

const ratesRequest = Array.from({ length: hotels.length }, (_, i) => ({
  endDate: new Date(new Date('2024-11-01').setDate(new Date('2024-11-01').getDate() + (i * 2) + 1)).toISOString().split('T')[0],
  startDate: new Date(new Date('2024-11-01').setDate(new Date('2024-11-01').getDate() + (i * 2))).toISOString().split('T')[0],
  hotel: hotels[i],  // city ID
  city: { country: '', id: 0, title: '', type: '' },
  adults: 2,
  children: [],
}));

// console.log(ratesRequest, 'ratesRequest');

export default ratesRequest;
